### ISSUE TITLE
新系统

### ISSUE THREAD

**Issue by astych666** [CQU-AI/cqu-kb#10]
换了新的选课系统，用的是统一认证号了，失效了

**Comment by 0xSeanll** [comment]
We are working on the new Unified Identity Authentication system right now.

**Comment by Hagb** [comment]
有将选课系统的 xlsx 或 json 转换成 ics 的轮子 https://github.com/weearc/cqu_timetable_new 和用 webdriver 访问选课系统的轮子 https://github.com/weearc/cm-http-api

**Comment by 0xSeanll** [comment]
> 有将选课系统的 xlsx 或 json 转换成 ics 的轮子 https://github.com/weearc/cqu_timetable_new 和用 webdriver 访问选课系统的轮子 https://github.com/weearc/cm-http-api

I am trying to avoid webdriver as much as I can.

**Comment by ilcpm** [comment]
我们在做现成的课程表ics导出，因为涉及到统一认证网站的登录，不方便把登录代码开源😂

**Comment by astych666** [comment]
> 有将选课系统的 xlsx 或 json 转换成 ics 的轮子 https://github.com/weearc/cqu_timetable_new 和用 webdriver 访问选课系统的轮子 https://github.com/weearc/cm-http-api

使用cqu_timetable_new的项目已成功导入，感谢诸位的付出

**Comment by Hagb** [comment]
> We are working on the new Unified Identity Authentication system right now.

现在有可供参考的开源轮子 https://github.com/DL444/cqu-schedule/blob/master/DL444.CquSchedule.Backend/Services/ScheduleService.cs
