### ISSUE TITLE
关于几处不合乎 RFC 5545 的地方

### ISSUE THREAD

**Issue by Hagb** [CQU-AI/cqu-kb#2]
- `VEVENT`中`dtstamp`和`uid`不可省略（https://icalendar.org/iCalendar-RFC-5545/3-6-1-event-component.html ）（另见 https://github.com/zombie110year/cli_cqu/pull/9 ）
- `TZID`涉及的时区需要有对应的`VTIMEZONE`（https://icalendar.org/iCalendar-RFC-5545/3-2-19-time-zone-identifier.html ）（另见 https://github.com/zombie110year/cli_cqu/pull/11 ）

**Comment by loopyme** [comment]
我尝试修复以上问题:
- #3 中添加了dtstamp与uid属性
- 关于`VTIMEZONE`，`cqu-kb`中使用了第三方库`pytz`来处理时区相关的问题，也许不需要加以调整?

**Comment by Hagb** [comment]
关于`VTIMEZONE`，是 RFC 5545 定义的 ics 文件的要求（如果我没有误读的话）。但`icalendar`读入带时区信息的时间时只会在`TZID`中写上时区名字，不会自动添加相应的`VTIMEZONE` component。（不过我还没见过无法读取这种非标 ics 的日历软件）

**Comment by loopyme** [comment]
> 关于`VTIMEZONE`，是 RFC 5545 定义的 ics 文件的要求（如果我没有误读的话）。但`icalendar`读入带时区信息的时间时只会在`TZID`中写上时区名字，不会自动添加相应的`VTIMEZONE` component。（不过我还没见过无法读取这种非标 ics 的日历软件）

感谢提示，昨天我搞错了。现在#3 已经能完美通过`iCalendar Validator`了.
